print(3 + 4)
print(3-4)
print(3 * 4)
print(3 % 4)
print(3 / 4)
print(3 ** 4)
print(3 // 4)

print("Zach")
print("Me")
print("Taiwan")
print("WOO")
print(type(10))
print(type(9.8))
print(type(4-4j))
print(type(['Asabeneh', 'Python', 'Finland']))
print(type("Zach"))
print(type("WOO"))
print(type("taiwan"))